### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by tarlepp** [Fbeen/UniqueSlugBundle#10]
Seems like current tests that this bundle contains has nothing to do with bundle itself.

You should write some tests for your bundle logic.

**Comment by Fbeen** [comment]
Tests has been added. Thanks Tarlepp.

**Comment by tarlepp** [comment]
You should really use proper commit messages to close issues - so that we could actually see what you did to solve each issue - https://help.github.com/en/articles/closing-issues-using-keywords
