### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by malutanpetronel** [Fbeen/UniqueSlugBundle#3]
Hi 
I am trying to run this in a script but apparently, the "yes" word is not passed to command, or if it is passed the command does not do anything:
**yes yes | app/console fbeen:generate:slugs --em=blog BloggerBlogBundle:Product --env=vlad**
however if I run it with
**app/console fbeen:generate:slugs --em=blog BloggerBlogBundle:Product --env=vlad**
and answer **yes** (enter) the slugs are generated

**Comment by tarlepp** [comment]
Hmm, why was this issue closed without any answer ?

**Comment by Fbeen** [comment]
The confirmation to generate slugs has been replaced by the option --regenerate in the latest release.

**Comment by malutanpetronel** [comment]
> Hmm, why was this issue closed without any answer ?

app/console fbeen:generate:slugs --em=blog BloggerBlogBundle:Product --env=vlad

After I asked I closed it myself as it was a question more about Linux and it worked without that yes part

**Comment by tarlepp** [comment]
Hmm I'm seeing that @Fbeen closed this issue - and that was the reason why asked why this was closed - just seems a bit weird if owner just closes issues without any real answer - imho.
