### ISSUE TITLE
Using return types?

### ISSUE THREAD

**Issue by tarlepp** [Fbeen/UniqueSlugBundle#7]
According to `composer.json` this bundle requires at least PHP version `7.0.8` - so what about using proper return types and maybe even strict type?

http://php.net/manual/en/migration70.new-features.php

**Comment by Fbeen** [comment]
Return types added wherever possible :-)

**Comment by tarlepp** [comment]
You should really use proper commit messages to close issues - so that we could actually see what you did to solve each issue - https://help.github.com/en/articles/closing-issues-using-keywords
