### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by tarlepp** [Fbeen/UniqueSlugBundle#8]
I'm seeing eg.

```
if($this->existSlug($oldSlug, $results))
{
    return $oldSlug;
}
```

So what about following - https://symfony.com/doc/current/contributing/code/standards.html ?

**Comment by Fbeen** [comment]
Code has been rewritten. If you have more issues please let me know.

**Comment by tarlepp** [comment]
With these kind of things you should at least add issue number to your commit - so that we could actually see what has been changed / fixed about this issue - I've noticed multiple similar things on current code - so - imho - this issue _isn't_ solved - and I cannot re-open this - so should I create a new one with same content?
