### ISSUE TITLE
Static analyzers?

### ISSUE THREAD

**Issue by tarlepp** [Fbeen/UniqueSlugBundle#9]
Have thinked using eg. tools like:
* [phpstan](https://github.com/phpstan/phpstan)
* [psalm](https://github.com/vimeo/psalm)

**Comment by Fbeen** [comment]
I have used phpstan. Works good! Thanks again.

**Comment by tarlepp** [comment]
And with this I mean - are you thinking to use those within this project? and there is a ton of more those which would help you avoid simple syntax things like eg. this line https://github.com/Fbeen/UniqueSlugBundle/blob/master/Tests/AnnotationReaderTest.php#L44

**Comment by tarlepp** [comment]
Hmm, why I cannot re-open this issue? Should I make a new one everytime?
